name: CI

on:
  push:
  pull_request:

jobs:
  unit-tests:
    strategy:
      matrix:
        go:
          - '^1.21'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./...
